### ISSUE TITLE
Gradle error

### ISSUE THREAD

**Issue by PiotrZakrzewski** [dspies/grails-3-with-security#2]
Hi,

I used your repo once for learning grails3 security, now I came back to it and tried to build the project after fresh clone. I get following error however:

> grails
> Picked up _JAVA_OPTIONS: -Xms2048m -Xmx4096m

BUILD SUCCESSFUL

Total time: 1.451 secs
| Error Error initializing classpath: Unsupported method: GrailsClasspath.getError().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model. (Use --stacktrace to see the full trace)

Do you know how to solve it?

cheers

**Comment by PiotrZakrzewski** [comment]
@dspies ?

**Comment by dspies** [comment]
Sounds like your version of Grails and/or Gradle is different than the one used to build the project.  You can either use gradlew to run the gradle tasks or if you want to run the latest versions of Grails and Gradle (Grails 3.0.8 and Gradle 2.7) update the following files as shown:

### build.gradle

```
buildscript {
    ...
    dependencies {
        ...
        classpath 'com.bertramlabs.plugins:asset-pipeline-gradle:2.5.0' // from 2.1.1
    }
}

plugins {
    id "io.spring.dependency-management" version "0.5.2.RELEASE" // from 0.3.1.RELEASE
}
```

### gradle.properties

```
grailsVersion=3.0.8
gradleWrapperVersion=2.7
```

Then, run `grails`

### Also, the [Grails Spring Security Plugin](https://grails-plugins.github.io/grails-spring-security-core/) is out
